### ISSUE TITLE
Label Ausgabe bearbeiten

### ISSUE THREAD

**Issue by KarstenBln** [JoomTools/plg_content_jteasylink#1]
Vorschlag Label: Ausgabe bearbeiten in "Skiplinks aktivieren" altivieren ändern.

**Comment by degobbis** [comment]
Hallo Karsten,
Danke für Deinen Vorschlag.

Mit der Option `Ausgabe bearbeiten` in den Plugin-Einstellungen soll tatsächlich die Möglichkeit gegeben werden die Ausgaben der jeweiligen Dokumente etwas an seine eigene Templateausgabe anzupassen, beginnend mit den Container-Elementen der jeweiligen Bereiche bis hin zu einer semantisch strukturierteren Ausgabe der Überschriften. 

Die Schnellnavigation (Skiplinks) ist aus systemtechnischen Gründen mit dieser Einstellung gekoppelt. Ein Umbenennen würde die eigentliche Funktion unkenntlich machen.

Aber ich sehe den Bedarf das besser zu Dokumentieren, deshalb denke ich, ist die bessere Vorgehensweise das in der Beschreibung deutlicher hervorzuheben (siehe issue #2).

Gruß Guido
