### ISSUE TITLE
Erklärung Nutzung Skiplinks

### ISSUE THREAD

**Issue by KarstenBln** [JoomTools/plg_content_jteasylink#2]
Hi Guido hier mein Vorschlag Ergänzung der Erklärung zu den Sprungmarken:

**Seit Version 1.0.3 kann auch eine Schnellnavigation angezeigt werden.**
Der Plugin-Aufruf ist {jteasylink skiplinks[,DOKUMENT,SPRACHKÜRZEL]}

Dieser Aufruf der Skiplinks muss zusätzlich zum Aufruf(Shortcode) für das Dokument gesetzt werden.

Beispielaufruf zur Anzeige der Skiplinks/Sprungmarken: {jteasylink skiplink,dse,de}
 Da dse und de die Standardwerte sind, kann Aufruf zu {jteasylink skiplink} vereinfacht werden.
Auch hier gelten die gleichen Standardwerte für DOKUMENT und SPRACHKÜRZEL und müssen somit nicht angegeben werden.

Der komplette Aufruf innerhalb eines Beitrags lautet: 
{jteasylink skiplink}
{jteasylink}

Das war es auch schon.

**Comment by degobbis** [comment]
Hallo Karsten,
Danke für Deinen Vorschlag.

Richtig ist, dass die Ausgabe der Schnellnavigation nur auf der Seite Sinn macht, auf der auch die Ausgabe des jeweiligen Dokuments angezeigt wird. Sie kann aber auch alleinstehen eingesetzt werden, z.B. in einem Modul.

Der springende Punkt ist jedoch, sie wird nur ausgegeben, wenn im Plugin die Einstellung `Ausgabe bearbeiten` aktiv ist und das sollte ich unbedingt in die Anleitung mit aufnehmen.

Gruß Guido

**Comment by degobbis** [comment]
Gelöst mit Version 1.0.5
